### ISSUE TITLE
unknown shorthand flag: 'f' in -f

### ISSUE THREAD

**Issue by Camis** [acdoussan/docker-migrate#1]
```
Copying volumes and compose to remote host
root@10.0.1.49's password:
vaultwarden-volumes.tar.gz                                                                                                                                                   100% 3887KB   4.9MB/s   00:00
root@10.0.1.49's password:
vaultwarden.compose.yml                                                                                                                                                      100% 1989   636.6KB/s   00:00
Creating container on remote host
root@10.0.1.49's password:
unknown shorthand flag: 'f' in -f
See 'docker --help'.
```

**Comment by acdoussan** [comment]
Hi there! Could you please provide the output of `docker inspect [container]` as well as full logs for the script by running `./docker-migrate.sh [regular commands] > output.txt 2>&1`

**Comment by acdoussan** [comment]
looks like this might be an issue with an old version of docker-compose, could you also provide your docker-compose version?

ref: https://github.com/docker/compose/issues/8986

**Comment by acdoussan** [comment]
the docker compose command is in the correct order based on the above post, ref: https://github.com/acdoussan/docker-migrate/blob/main/docker-migrate.sh#L82

I suspect you have an old version of docker that doesn't have the v2 docker compose version installed, ref: https://stackoverflow.com/a/66516826

I'll update the list of requirements to call this out, but please verify that this is the case.

**Comment by acdoussan** [comment]
stale, resolving, please open a new issue if you are still having problems
