### ISSUE TITLE
Script Error while creating container on remote host

### ISSUE THREAD

**Issue by S4nfs** [acdoussan/docker-migrate#2]
Having this error while migrating to another host: (Docker V2 installed on both but not the same version)

```
Creating container on remote host
unknown shorthand flag: 'f' in -f
```

**Comment by acdoussan** [comment]
please see https://github.com/acdoussan/docker-migrate/issues/1

**Comment by acdoussan** [comment]
if ^ doesn't resolve your issue please reopen / create a new issue and provide the info requested in that issue.
